### ISSUE TITLE
Don't import nameidformat for IdPs

### ISSUE THREAD

**Issue by baszoetekouw** [OpenConext/OpenConext-manage#133] opened 2024-08-27 15:50 UTC
Because we don't need this., and it this is broken for ADFS, see https://servicedesk.surf.nl/jira/browse/CXT-78059

**Comment by oharsta** [comment] 2024-11-08 10:50
Duplicate of https://github.com/OpenConext/OpenConext-manage/issues/447

**Closed by oharsta** 2024-11-08 10:50 UTC
