### ISSUE TITLE
saml20_idp: export/import Service Providers Whitelist (as e.g. csv )

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-manage#429] opened 2024-10-14 20:50 UTC
[This issue is imported from pivotal - Originaly created at Jul 26, 2024 by andreklaver](https://www.pivotaltracker.com/story/show/188018695)

Import, Export  Service Providers Whitelist from an IdP as (e.g.) a CSV. 

This will help when migrating/creating an IdP to whitelist previously connected services or other entities (default services) needed when creating an IdP.

**Comment by thijskh** [comment] 2024-12-16 10:35
Duplicate of #430

**Closed by thijskh** 2024-12-16 10:35 UTC
Labels: Imported
